# Generated by Django 3.2.13 on 2022-11-24 07:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_staffnotificationstudent'),
    ]

    operations = [
        migrations.AddField(
            model_name='staffnotificationstudent',
            name='staff',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='main_app.instructor'),
            preserve_default=False,
        ),
    ]
