# Generated by Django 3.2.13 on 2022-11-24 10:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_sudentsubjects'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentresult',
            name='exam',
        ),
        migrations.RemoveField(
            model_name='studentresult',
            name='test',
        ),
        migrations.AddField(
            model_name='studentresult',
            name='assignment1',
            field=models.FloatField(default=0, verbose_name='Assignment 1'),
        ),
        migrations.AddField(
            model_name='studentresult',
            name='assignment2',
            field=models.FloatField(default=0, verbose_name='Assignment 2'),
        ),
        migrations.AddField(
            model_name='studentresult',
            name='assignment3',
            field=models.FloatField(default=0, verbose_name='Assignment 3'),
        ),
        migrations.AddField(
            model_name='studentresult',
            name='assignment4',
            field=models.FloatField(default=0, verbose_name='Assignment 4'),
        ),
        migrations.AddField(
            model_name='studentresult',
            name='mid1',
            field=models.FloatField(default=0, verbose_name='Mid 1'),
        ),
        migrations.AddField(
            model_name='studentresult',
            name='mid2',
            field=models.FloatField(default=0, verbose_name='Mid 2'),
        ),
        migrations.CreateModel(
            name='StudentNotificationStaff',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.instructor')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.student')),
            ],
        ),
    ]
