# Generated by Django 3.2.13 on 2022-11-24 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_auto_20221124_0425'),
    ]

    operations = [
        migrations.AddField(
            model_name='staffnotificationstudent',
            name='sender',
            field=models.TextField(default='staff'),
            preserve_default=False,
        ),
    ]
